environment:
  matrix:
    - nodejs_version: "5.8.0"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - node -v
  - npm install -g npm
  - npm install

test_script:
  - npm test

build: off
deploy: off